#for x86_64
FROM centos:8

#for aarch64
#FROM docker.io/arm64v8/centos

LABEL maintainer="greatsql.cn" \
email="greatsql@greatdb.com" \
forum="https://greatsql.cn/forum.php" \
gitee="https://gitee.com/GreatSQL/GreatSQL-Shell-Docker"

ENV LANG en_US.utf8
ARG INSTALL_PKG="libssh python38 python38-libs python38-pyyaml" \
MYSQLSH="greatsql-shell-8.0.32-25-centos-glibc2.28-x86_64" \
BASE_DIR=/usr/local
#for aarch64
#MYSQLSH="greatsql-shell-8.0.32-25-centos-glibc2.28-aarch64" \

COPY ${MYSQLSH}.tar.xz ${BASE_DIR}

RUN unlink /etc/localtime; ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime ; \
rm -f /etc/yum.repos.d/CentOS-Linux-* ; \
curl -o /etc/yum.repos.d/CentOS-Base.repo https://mirrors.aliyun.com/repo/Centos-vault-8.5.2111.repo && \
sed -i -e '/mirrors.cloud.aliyuncs.com/d' -e '/mirrors.aliyuncs.com/d' /etc/yum.repos.d/CentOS-Base.repo && \
yum clean all > /dev/null 2>&1 && \
yum -y update > /dev/null 2>&1 ; \
rm -f /etc/yum.repos.d/CentOS-Linux-* ; \
yum clean all > /dev/null 2>&1 && \
rm -f /etc/yum.repos.d/CentOS-Linux-* ; \
yum install -y ${INSTALL_PKG} > /dev/null 2>&1 ; \
pip3.8 install --user certifi > /dev/null 2>&1 && \
tar xf ${BASE_DIR}/${MYSQLSH}.tar.xz -C ${BASE_DIR} > /dev/null 2>&1 && \
ln -s ${BASE_DIR}/${MYSQLSH}/bin/mysqlsh ${BASE_DIR}/bin/mysqlsh

CMD ["bash"]
